# Generated by Django 4.0.4 on 2022-04-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='teachers/defaultImage3.jpg', upload_to='teachers/%Y/%m/%d'),
        ),
    ]
