# Generated by Django 4.0.4 on 2022-04-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/defaultImage2.png', upload_to='courses/%Y/%m/%d'),
        ),
    ]
